# Generated by Django 5.0.6 on 2024-07-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='currency_fair',
            field=models.TextField(blank=True, null=True),
        ),
    ]
